# URL: https://leetcode.com/problems/find-the-difference/description/
# Description: You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.
# Constraints: 0 <= s.length <= 1000 -- t.length == s.length + 1 -- s and t consist of lowercase English letters.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_list = list(s); t_list = list(t); letters = list('abcdefghijklmnopqrstuvwxyz')
        if len(s) >= 0 and len(s) <= 1000 and len(t) == len(s) + 1 and all(letter in letters for letter in s_list) and all(letter in letters for letter in t_list):
            for letter in s_list:
                if letter in t_list: t_list.pop(t_list.index(letter))
            return ''.join(t_list)

solution = Solution()